spring:
  application:
    name: shrink-me
  datasource:
    url: jdbc:mysql://localhost:3306/shrink_me?createDatabaseIfNotExist=true 
    username: root
    password: root

websiteUrl: http://localhost:8080/

default-ttl-minutes: 2
